
package clientesoracleapp;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
public class FormularioNuevoClienteProyecto extends javax.swing.JFrame {

    
     private JTextField txtIDCliente, txtDNI, txtNombreCliente, txtIDProyecto, txtNombreProyecto, txtFechaContrato, txtDetalleContrato;
    private JButton btnGuardar, btnCancelar;

    public FormularioNuevoClienteProyecto() {
        setTitle("Nuevo Cliente-Proyecto");
        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        // Panel de entrada
        JPanel panelCampos = new JPanel(new GridLayout(7, 2, 10, 10));
        panelCampos.setBorder(BorderFactory.createEmptyBorder(20, 20, 10, 20));

        txtIDCliente = new JTextField();
        txtDNI = new JTextField();
        txtNombreCliente = new JTextField();
        txtIDProyecto = new JTextField();
        txtNombreProyecto = new JTextField();
        txtFechaContrato = new JTextField();
        txtDetalleContrato = new JTextField();

        JTextField[] campos = {
            txtIDCliente, txtDNI, txtNombreCliente, txtIDProyecto,
            txtNombreProyecto, txtFechaContrato, txtDetalleContrato
        };

        for (JTextField campo : campos) {
            campo.setPreferredSize(new Dimension(250, 30));
            campo.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        }

        panelCampos.add(new JLabel("Ingresar ID Cliente:"));
        panelCampos.add(txtIDCliente);
        panelCampos.add(new JLabel("Ingresar DNI:"));
        panelCampos.add(txtDNI);
        panelCampos.add(new JLabel("Ingresar Nombre Cliente:"));
        panelCampos.add(txtNombreCliente);
        panelCampos.add(new JLabel("Ingresar ID Proyecto:"));
        panelCampos.add(txtIDProyecto);
        panelCampos.add(new JLabel("Ingresar Nombre Proyecto:"));
        panelCampos.add(txtNombreProyecto);
        panelCampos.add(new JLabel("Ingresar Fecha Contrato (YYYY-MM-DD):"));
        panelCampos.add(txtFechaContrato);
        panelCampos.add(new JLabel("Ingresar Detalle Contrato:"));
        panelCampos.add(txtDetalleContrato);

        // Panel de botones
        JPanel panelBotones = new JPanel();
        btnGuardar = new JButton("Guardar");
        btnCancelar = new JButton("Cancelar");
        panelBotones.add(btnGuardar);
        panelBotones.add(btnCancelar);

        add(panelCampos, BorderLayout.CENTER);
        add(panelBotones, BorderLayout.SOUTH);

        // Acción botón Guardar
        btnGuardar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                guardarDatos();
            }
        });

        // Acción botón Cancelar
        btnCancelar.addActionListener(e -> dispose());
    }

    private void guardarDatos() {
        String idCliente = txtIDCliente.getText();
        String dni = txtDNI.getText();
        String nombreCliente = txtNombreCliente.getText();
        String idProyecto = txtIDProyecto.getText();
        String nombreProyecto = txtNombreProyecto.getText();
        String fechaContrato = txtFechaContrato.getText();
        String detalleContrato = txtDetalleContrato.getText();

        try (Connection conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "Oracle")) {
            String sql = "INSERT INTO CLIENTE_PROYECTO (ID_CLIENTE, DNI, NOMBRE_CLIENTE, ID_PROYECTO, NOMBRE_PROYECTO, FECHA_CONTRATO, DETALLE_CONTRATO) " +
                         "VALUES (?, ?, ?, ?, ?, TO_DATE(?, 'YYYY-MM-DD'), ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, idCliente);
            stmt.setString(2, dni);
            stmt.setString(3, nombreCliente);
            stmt.setString(4, idProyecto);
            stmt.setString(5, nombreProyecto);
            stmt.setString(6, fechaContrato);
            stmt.setString(7, detalleContrato);

            int filasInsertadas = stmt.executeUpdate();
            if (filasInsertadas > 0) {
                JOptionPane.showMessageDialog(this, "Registro guardado correctamente.");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar los datos.");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error en la base de datos: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioNuevoClienteProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioNuevoClienteProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioNuevoClienteProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioNuevoClienteProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioNuevoClienteProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
